Feat/9 impl restaurant api
ShinBeomsoo/capstone_design_3 pull request #10
Opened 2024-04-18 11:05 UTC by ssoyeong-lee

# API 내역
- [x] /restaurants
- [x] /restaurants/{id}
- [x] /mobums
- [x] /mobums/{id}
- [ ] /measures
- [ ] /measures/{id}

# 설명
## API
- `/resource`는 각 테이블의 필수 칼럼만 리스트 형태로 제공하고, `/resource/{id}`는 특정 id값을 가진 행의 모든 칼럼을 제공합니다.
## 문제점
measure의 경우, 테이블을 info와 data로 나누어 설계하였습니다. 교부번호를 이용하여 info에서 특정음식점이 행정처분을 한 번이라도 받는 적이 있는지 판단한 후, data에서 해당 음식점의 행정처분 내역을 가지고 오려고 시도했습니다...! 하지만 교부번호가 중복으로 할당된 음식점이 존재해 이 방식은 사용이 불가능합니다.
##  수정 방안(예정)
measure_info, measure_data => measure 하나의 테이블에서 관리, 이에 따른 api도 변경 예정입니다.

2024-04-21 11:55 UTC, ssoyeong-lee commented
- 각 api에 쿼리 파라미터 추가
- 쿼리, 패스 파라미터에 유효성 검사 부분 추가
- python3.10+에 맞춘 리펙터링

2024-04-21 16:15 UTC, ShinBeomsoo reviewed
실행하면서 보였던 거 위주로 우선 작성했습니다!

(무엇보다 3.9랑 3.10이 차이가 있어서 당황했습니다...ㅠ 그래서 3.10으로 맞춰서 코딩하려고 합니다!)

2024-04-21 16:15 UTC, ShinBeomsoo commented on back/app/api/api.py
> +api_router.include_router(restaurant.router, prefix="/restaurants", tags=["rastaurant"])
typo: rastaurant -> restaurant

2024-04-21 16:15 UTC, ShinBeomsoo commented on back/app/api/endpoints/measure.py
> +    name: Annotated[str | None, Query()] = None,
https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#declare-more-metadata

여기를 참고해보시면 query parameter에도 description을 추가할 수 있습니다! 한번 해보면 좋을 거 같아요!

2024-04-21 16:15 UTC, ShinBeomsoo commented on back/app/api/endpoints/measure.py
> +    return info
return 되는 좌표가 공공데이터에 의하면 아래와 같이 설명이 되어있습니다! [참고](https://data.seoul.go.kr/dataList/OA-18674/S/1/datasetView.do)

-> 좌표안내 : 중부원점TM(EPSG:2097) 좌표계에 따른 해당위치의 좌표정보이며 위경도 좌표는 제공하고 있지 않음

제 느낌엔 위도 경도 좌표로 변경되어야 아마,,, front에서 적용할 때 편하지 않을까 생각이 듭니다... 한번 찾아봐야할 듯 합니다.

2024-04-21 16:15 UTC, ShinBeomsoo commented on back/app/api/endpoints/mobum.py
> +    name: Annotated[str | None, Query()] = None,
name에 관한 parameter로 이도곰탕을 주었을 때는 이도곰탕에 대한 정확한 값이 오나

"이도곰"만 주었을 때는 empty list가 오는 거 같습니다! (http://localhost:8000/v1/restaurants?name=이도 이걸로 test 했습니다.)
이도곰 혹은 잘못된 parameter값이 오면 그거에 대한 예외처리를 해야할 거 같아요!

2024-04-21 16:16 UTC, ShinBeomsoo commented on back/app/api/endpoints/mobum.py
> +    name: Annotated[str | None, Query()] = None,
현재는 "이도곰"만 주면 return 이 [] 로 옵니다!

2024-04-21 16:20 UTC, ShinBeomsoo requested changes

2024-04-21 16:20 UTC, ShinBeomsoo commented on back/app/api/endpoints/mobum.py
> +    best: Annotated[str | None, Query()] = None,
best -> best_food로 하는게 더 naming이 좋아보입니다! 아니면 cuisine 이런 표현도 있습니다!

2024-04-26 09:13 UTC, ssoyeong-lee commented on back/app/api/api.py
> +api_router.include_router(restaurant.router, prefix="/restaurants", tags=["rastaurant"])
해결했습니다!

2024-04-26 09:14 UTC, ssoyeong-lee commented on back/app/api/endpoints/mobum.py
> +    best: Annotated[str | None, Query()] = None,
best_food로 수정했습니다!

2024-04-27 05:20 UTC, ssoyeong-lee commented on back/app/api/endpoints/mobum.py
> +    name: Annotated[str | None, Query()] = None,
`name=이`를 주어도 사업장명에 `이`가 포함된 모든 음식점을 리턴하라는 말씀이신거죠? 
잘못된 파라미터와 예외처리는 어떤 걸 말씀하시는 걸까요? 일치하는 값이 없을 때, body에 뭘 담아서 리턴해야 하나요??

2024-04-27 05:21 UTC, ssoyeong-lee commented on back/app/api/endpoints/measure.py
> +    return info
일단 DB에 중부원점 좌표계로 저장되어 있는 상태라, 응답 할 때마다 변경해서 보내도록 수정해볼게요...!

2024-04-29 13:53 UTC, ShinBeomsoo commented on back/app/api/endpoints/mobum.py
> +    name: Annotated[str | None, Query()] = None,
chatGPT의 instruction을 통해 해결하는 걸로 결론!

2024-04-29 13:55 UTC, ShinBeomsoo commented on back/app/api/endpoints/measure.py
> +    return info
오승민 교수님 왈: 아무거나 해도 상관없을 듯! 하지만 두 개다 비교해서 공부해보는 것도 나쁘지 않을 거 같다.

2024-04-29 14:02 UTC, ShinBeomsoo commented
LGTM

2024-04-29 14:02 UTC, merged